{% set name = "types-cachetools" %}
{% set version = "5.4.0.20240717" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/types-cachetools-{{ version }}.tar.gz
  sha256: 1eae90c48760bac44ab89108be938e8ce1d740910f2d4b68446dcdc82763f186

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  commands:
    - test -f $SP_DIR/cachetools-stubs/__init__.pyi


about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for cachetools
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
